[tool.poetry]
name = "pylink_utils"
version = "1.2.4"
description = ""
authors = ["douglas-peter <76939369+douglas-peter@users.noreply.github.com>"]
homepage = "https://github.com/Pylink-Analytics/pylink_utils"
repository = "https://github.com/Pylink-Analytics/pylink_utils"
license = "MIT"
include = [
    "LICENSE",
]
[tool.poetry.dependencies]
python = ">=3.8,<3.11"
bs4 = "0.0.1"
lxml = "4.8.0"
awswrangler = "^2.16.1"
boto3 = "^1.24.46"
pandas = "^1.4.3"
botocore = "^1.27.46"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
