[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "optiQs"
version = "0.0.1"
authors = [
  { name="Sammith S Bharadwaj", email="sammithsb@gmail.com" },
]
description = "Simulation of quantum optic elements"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/SammithSB/qwanta"
"Bug Tracker" = "https://github.com/SammithSB/qwanta/issues"