[tool.poetry]
name = "ky3m"
version = "0.2.3.dev1"
description = "Minecraft Mod Manager by Leon \"Procybit\" Shepelev"
authors = ["Leon \"Procybit\" Shepelev <kyleusnaff@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Procybit/Ky3M"
keywords = ["minecraft"]
packages = [
    { include = "ky3m" },
]

[tool.poetry.dependencies]
python = "^3.10"
toml = "~0.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Report a bug!" = "https://github.com/Procybit/Ky3M/issues"
