[tool.poetry]
name = "cradlebio"
version = "0.1.17"
description = "Client for Cradle's Alphafold-as-a-service"
authors = ["Cradle Bio <info@cradle.bio>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.7"
biopython = "^1.70"
google-cloud-firestore = "^2.4.0"
google-cloud-storage = "^2.2.1"
google-auth = "^2.6"
google-api-python-client = "^2.42.0"
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-mock = "^3.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_level = "DEBUG"
log_file = ".pytest_cache/logs/pytest-logs.txt"
addopts = "--full-trace"
