[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hero-test"
authors = [
    { name = "hero.park", email = "blurabbity@gmail.com" },
]
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    'jsonschema == 4.6.2'
]
version = "0.0.1"
description = "test project"

[tool.flit.module]
name = "hero"

[project.urls]
Home = "https://github.com/hyunwoo91/hero-test"
