[tool.poetry]
name = "jqlite"
version = "0.4.0"
description = "A lightweight implementation of jq."
authors = ["Christian <xian.tuxoid@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7.0"
typer = {version = "^0.6.1", extras = ["all"]}
termcolor = "^1.1.0"
more-itertools = "^8.14.0"
orjson = "^3.7.11"
pyrsistent = "^0.18.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pre-commit = "^2.20.0"

[tool.poetry.scripts]
jqlite = "jqlite.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
